# Generated by Django 3.2 on 2021-05-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorty',
            old_name='long',
            new_name='long_url',
        ),
        migrations.RenameField(
            model_name='shorty',
            old_name='short',
            new_name='short_url',
        ),
    ]
